DROP TABLE IF EXISTS Sessions;
DROP TABLE IF EXISTS EventLogs;
DROP TABLE IF EXISTS Letters;
DROP TABLE IF EXISTS Images;
DROP TABLE IF EXISTS OTP_admin;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Event_types;
DROP TABLE IF EXISTS Rol;
